### ISSUE TITLE
Multiple Database Connections

### ISSUE THREAD

**Issue by NBA707** [rayVenues/eloquent-model-generator#10]
Is it possible to specify the database connection used in model generation?   I have 6 databases my systsem accesses and it would be nice to be able to generate a model for the non-default database.

**Comment by ricardoaponte** [comment]
Hello @NBA707, have you tried the --connection option? You can specify the model connection there.

**Comment by NBA707** [comment]
Yes, found that after posting the question.

**Comment by NBA707** [comment]
Yes, found that and it says pqsql is not supported.
